### ISSUE TITLE
Successfully loaded 0 gists from your Account.

### ISSUE THREAD

**Issue by greyscalecom** [crealytics/adscriptor#6]
This is not correct. I have given it permissions for gist, I have 1 public and 1 private. Didn't seem to find any of them.

**Comment by Turtlefight** [comment]
Hi greyscalecom,
did you create the gists with AdScriptor?
AdScriptor only recognises Gists created by itself (it needs to append a small startup script to bootstrap the environment).

Otherwise you could to log off from AdScriptor & re-enter the token, maybe something in its internal state got messed up :)

Have a nice week,
Sven Fisch
